### ISSUE TITLE
Bug: Link to code on github not working?

### ISSUE THREAD

**Issue by barnett11** [pharmaverse/datacutr#184]
### What happened?

Source link at top of pages such as https://pharmaverse.github.io/datacutr/main/reference/apply_cut.html not resolving

**Comment by barnett11** [comment]
admiral comparison in pkgdwn.yml `source` - https://github.com/pharmaverse/admiral/blob/main/

**Comment by alanaharris22** [comment]
Updated. See PR here - https://github.com/pharmaverse/datacutr/pull/186
