### ISSUE TITLE
Create DCUT function

### ISSUE THREAD

**Issue by alanaharris22** [pharmaverse/datacutr#47]

**Comment by barnett11** [comment]
Hi @alanaharris22 
This function needs to check the DS filter record dates against DCUT date, and remove those after that date ie. if patient was radnomized after datacut date, they are excluded from DCUT (and will be removed from future dcut processing)

**Comment by alanaharris22** [comment]
Hi @barnett11, I have updated the ordering of the filter condition in the dataset creation so this can be added as part of the filter parameter (e.g. filter = DSDECOD == "RANDOMIZATION" & DCUTDT>=DCUT_TEMP_DSSTDTC (where we create the imputed DSSTDTC date in a previous step)). Have updated the example script too - let me know what you think, though this could make the function a bit more flexible. Thanks!
