### ISSUE TITLE
Testing on full study test case

### ISSUE THREAD

**Issue by barnett11** [pharmaverse/datacutr#98]
Full test on a full study - ideally large Ph3
@reesnj @alanaharris22 for proposed study/location

**Comment by alanaharris22** [comment]
Hi @barnett11, 
I checked with Mike, we can use the NP30179 study. 
Although since it's currently going througha filing, he asked if we could possibly use an older snapshot of SDTMv (~Nov 2021). 
eICE Location - root/clinical_studies/RO7082859/CDT70029/NP30179
Thanks, 
Alana

**Comment by barnett11** [comment]
That should be perfect thanks, will setup

**Comment by barnett11** [comment]
Full test completed - https://code.roche.com/barnett1/datacutr_testing/-/tree/devel
